version: '3.8'

services:
  # База данных PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: telegram_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_strong_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: telegram_bot
      DB_USER: postgres
      DB_PASSWORD: 1111
      DB_PORT: 5432
      
      BOT_TOKEN: "8277658469:AAEYWH4eb8PkPyxDGO-H7UKe-hatBIFhFZk"
    
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs  # Папка для логов

volumes:
  postgres_data:

